services:
  - type: web
    name: ai-job-agent-backend
    env: python
    plan: free # no disk allowed
    rootDir: backend
    autoDeploy: true
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn ai_job_agent.apps.api.main:app --app-dir src --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: src
      - key: EMBEDDINGS_PROVIDER
        value: gemini
      - key: GEMINI_EMBEDDINGS_MODEL
        value: models/embedding-001
      # put DB & Chroma in ephemeral /tmp
      - key: DATA_DIR
        value: /tmp/data
      - key: SQLITE_URL
        value: sqlite:////tmp/data/ai_job_agent.db
      - key: CHROMA_DIR
        value: /tmp/data/chroma_store
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false

  - type: web
    name: ai-job-agent-frontend
    env: python
    plan: free
    rootDir: frontend
    autoDeploy: true
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
    healthCheckPath: /
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: ai-job-agent-backend
          property: host
