services:
  - type: web
    name: ai-job-agent-backend
    env: python
    plan: free
    rootDir: backend
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn ai_job_agent.apps.api.main:app --app-dir src --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: src
      - key: EMBEDDINGS_PROVIDER
        value: gemini
      - key: GEMINI_EMBEDDINGS_MODEL
        value: models/embedding-001
      # Use /tmp for free plan (resets on deploys/restarts)
      - key: DATA_DIR
        value: /tmp/data
      - key: SQLITE_URL
        value: sqlite:////tmp/data/ai_job_agent.db
      - key: CHROMA_DIR
        value: /tmp/data/chroma_store
      # Secrets → set values in Render dashboard after import
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
